### ISSUE TITLE
Why not use *gin.Context in gin wrapper ??

### ISSUE THREAD

**Issue by silenaker** [ShiningRush/droplet#16]
I see the wraps code use request.Context() like this `dCtx.SetContext(input.Req.Context())` how do id use the gin context values set by gin middlewares ?? this is really not a design problem, right?

**Comment by caojianfei** [comment]
I have the same question. Now we can not use gin.Context, so we can not use the keys in gin.Context, like a logined user set in gin.Context keys.

**Comment by ShiningRush** [comment]
Hi, all, it is not a design problem, `droplet` is used to decouple concrete framework and business logic, so we can not use the `gin.Context` directly, it will cause you can not switch web framework swiftly.
Maybe we can save all data of `gin.Context` to `context.Context` or `droplet.Context`?
