### ISSUE TITLE
Feat: need a way to get request body

### ISSUE THREAD

**Issue by starsz** [ShiningRush/droplet#2]
Hello. Now there is no way to get the request body in gin's hander. because you read the body to inject field.
I think it's needed to save the request body for other use.

IMO there are two ways to do this:

1. Set the dict with the request body when reading the body.
2. Use a buffer to save the request body and implate the `http.Request`s GetBody function.

**Comment by ShiningRush** [comment]
Hi, Here are two way to get request's body
- Droplet have already inject the original `http.Request` to `droplet.Context` with key `HttpRequest` , you can use it
- Using build-in variable name `@body`, please have look at [here](https://github.com/ShiningRush/droplet/blob/master/wrapper/gin/examples/main.go#L22)

**Comment by starsz** [comment]
Pretty good.
