### ISSUE TITLE
Feat: droplet.Context can save the gin.Context

### ISSUE THREAD

**Issue by starsz** [ShiningRush/droplet#3]
In some situations, we need to use gin.Context to save the key and value in the  middleware.But now, I can't find a way to get the gin.Context though droplect.Context.

See :https://github.com/ShiningRush/droplet/blob/51909e501bf4bc18743c912eda768b6feaafa8a6/wrapper/gin/gin.go#L23

So I recommend adding a field to save the gin.Context.Then we can get the gin.Context in our interface handler.

**Comment by ShiningRush** [comment]
Droplet is designed to prevent user care concrete logic, so we can not inject gin's context
