### ISSUE TITLE
bug: get request occurs error in binding query param

### ISSUE THREAD

**Issue by jujiale** [ShiningRush/droplet#35]
**version**:
        github.com/shiningrush/droplet v0.3.0
	github.com/shiningrush/droplet/wrapper/gin v0.2.1

**phenomenon**
when a requst use get method carry query param. it's param binding occurs error. different param order appears different phenomenon.
the following is my test:
1. this is my struct
`
  
       type GetTestInput struct {
	    PageSize   int `json:"pageSize" form:"pageSize" auto_read:"pageSize"`
	    PageNumber int `json:"pageNum" form:"pageNum" auto_read:"pageNum"`
	    ClusterId  int    `auto_read:"ClusterId,header" json:"ClusterId"`
	    InnerAddr  string `auto_read:"innerAddr,query" json:"innerAddr"`
	    OutterAddr string `auto_read:"outterAddr,query" json:"outterAddr"`
	    Path       string `auto_read:"path,query" json:"path"`
	    Status     *int   `auto_read:"status,query" json:"status"`
	    Labels     string `auto_read:"labels,query" json:"labels"`
	    HomeUnit   *int   `auto_read:"homeUnit,query" json:"homeUnit"`
        }

  
`
when I use the above struct and send the following request:
(the ClusterId is in header)
http://127.0.0.1:8080/api/v1/test?labels=aaa&pageNum=1&pageSize=50&homeUnit=1
![image](https://user-images.githubusercontent.com/48037235/227221698-bd71085b-ffa7-4c26-ae39-b31a5b396be4.png)

when I use the following struct(it just change the property order ):
`
  
       type GetTestInput struct {
            Labels     string `auto_read:"labels,query" json:"labels"`
	    PageSize   int `json:"pageSize" form:"pageSize" auto_read:"pageSize"`
	    PageNumber int `json:"pageNum" form:"pageNum" auto_read:"pageNum"`
	    ClusterId  int    `auto_read:"ClusterId,header" json:"ClusterId"`
	    InnerAddr  string `auto_read:"innerAddr,query" json:"innerAddr"`
	    OutterAddr string `auto_read:"outterAddr,query" json:"outterAddr"`
	    Path       string `auto_read:"path,query" json:"path"`
	    Status     *int   `auto_read:"status,query" json:"status"`
	    HomeUnit   *int   `auto_read:"homeUnit,query" json:"homeUnit"`
        }

 
`
then I use the above struct and send the following request:
http://127.0.0.1:8080/api/v1/test?labels=aaa&pageNum=1&pageSize=50&homeUnit=1
it appears as below:
![image](https://user-images.githubusercontent.com/48037235/227222921-9dd52df2-c9dd-4154-8e7e-592b3eb51f3e.png)

please pay attention to "labels", just change the order in the same struct. one could get it's value. the other don't

I want to know why this occurs.

**Comment by jujiale** [comment]
when I add validate tag in property Lables as following.
`

          Labels     string `auto_read:"labels,query" json:"labels" validate:"required"`

`

then I send request with the lables. but as I metioned above. as the following , it seems droplet didnot get the param.


![image](https://user-images.githubusercontent.com/48037235/227230861-3c35c100-bc49-43bc-abe9-92f892070e94.png)

**Comment by ShiningRush** [comment]
I'm sorry to reply so lated.
It's  a bug that, when you don't give a value to a pointer field, will cause function returned so that other fields could not be handled.

I have fixed in #38.
